cargo-features = ["edition2024"]

[package]
name = "system"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "*"
leptos = { version = "*", features = ["csr", "nightly"] }
